format = "$time$all$username$directory$character"


[nodejs]
format = '[$symbol]($style)'

[python]
format = '[$symbol]($style)'

[ruby]
format = '[$symbol]($style)'

[git_branch]
symbol = "ğŸŒ± "
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_status]
style= "blue"
conflicted = "ğŸ³"
up_to_date = "ğŸŸ¢"
untracked = "âœ¨"
modified = "âš™ "
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

ahead = "ğŸ’¨â‡¡${count}"
diverged = "ğŸ˜µâ‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "ğŸ˜°â‡£${count}"
staged = '[++\($countğŸ“¦\)](green)'

[time]
disabled = false
format = '[$time]($style) '
style = 'yellow'

[directory]
truncation_length = 8